spring:
  freemarker:
    cache: false
    template-loader-path:
      - classpath:/templates/
    prefix:
    suffix: .html
  resources:
    static-locations:
      - classpath:/static/
  devtools:
    restart:
      enabled: true
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.lob.non_contextual_create: true
una:
  master:
    datasource:
      url: jdbc:postgresql://localhost:5432/saas
      username: postgres
      password: admin
      driverClassName: org.postgresql.Driver
      maxPoolSize: 10
      idleTimeout: 300000
      minIdle: 10
      poolName: master-database-connection-pool
logging:
  level:
    root: info
    org:
      springframework:
        web: debug
      hibernate: debug
